"""add paper summary cache columns

Revision ID: 8fb9aa9ceb94
Revises: aaa169796905
Create Date: 2026-08-29 16:28:10.033896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb9aa9ceb94'
down_revision: Union[str, Sequence[str], None] = 'aaa169796905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_papers', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('uploaded_papers', sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('uploaded_papers', 'summary_generated_at')
    op.drop_column('uploaded_papers', 'summary')
    # ### end Alembic commands ###
