"""add last_viewed_at to uploaded papers

Revision ID: 948362a75e35
Revises: e08a96f36094
Create Date: 2026-09-05 13:07:17.591017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948362a75e35'
down_revision: Union[str, Sequence[str], None] = 'e08a96f36094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_papers', sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_uploaded_papers_last_viewed_at'), 'uploaded_papers', ['last_viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_papers_last_viewed_at'), table_name='uploaded_papers')
    op.drop_column('uploaded_papers', 'last_viewed_at')
    # ### end Alembic commands ###
