"""add chat session papers association table

Revision ID: e08a96f36094
Revises: 8fb9aa9ceb94
Create Date: 2026-09-01 16:14:59.660589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08a96f36094'
down_revision: Union[str, Sequence[str], None] = '8fb9aa9ceb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_papers',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['uploaded_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'paper_id')
    )
    # ### end Alembic commands ###

    # Backfill: every existing session's single anchor paper_id becomes a row
    # here too, so retrieval/ownership checks can go through this table
    # uniformly for old and new sessions alike.
    op.execute(
        "INSERT INTO chat_session_papers (session_id, paper_id) "
        "SELECT id, paper_id FROM chat_sessions WHERE paper_id IS NOT NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_session_papers')
    # ### end Alembic commands ###
